export const DIRECTOR_MESSAGE = `
query{
  aboutUs{
    data{
      attributes{
        DirectorMessage{
          id
          directorName
          designation
          message
          directorImage{
            data{
              attributes{
                url
              }
            }
          }
        }
      }
    }
  }
}`;
export const EMPOWERMENTS = `
query{
  aboutUs{
    data{
      attributes{
        Empowerments{
          id
          Title
          Subtitle
          Description
          Images{
            data{
              attributes{
                url
              }
            }
          }
        }
      }
    }
  }
}`;
export const BRAND_VALUES = `
query{
  aboutUs{
   data{
    attributes{
      brand_value{
        data{
          attributes{
            BrandValues{
               id
              Title
              SubTitle
              Body
              Images{
                data{
                  attributes{
                    url
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
}`;
export const MISIONVISION = `
  query{
  missionVisions{
    data{
      attributes{
        MissionVision{
          id
          Title
          SubTitle
          Description
          Images{
            data{
              attributes{
                url
              }
            }
          }
          alignment{
            data{
              attributes{
                Alignment{
                  Title
                }
              }
            }
          }
        }
      }
    }
  }

}`;
export const INNOVATIONS = `
query{
  innovations{
    data{
      id
      attributes{
        Innovation{
          id
          Title
          SubTitle
          Body
          Images{
            data{
              attributes{
                url
              }
            }
          }
        }
        counter{
          data{
            id
            attributes{
              AboutCounter{
                id
                counter
                CounterDesc
              }
            }
          }
        }
      }
    }
  }
}`;
